const palette = {
    olive: '#8AA624',
    oliveDark: '#6B8A1A',
    oliveDeeper: '#4E6612',
    sage: '#DBE4C9',
    sageDark: '#C5D5A8',
    amber: '#FEA405',
    amberDark: '#D98C00',
};

export const Colors = {
  light: {
    background:   '#F4F7EC',
    card:         '#FFFFFF',
    input:        '#EFF3E4',
    muted:        '#E6EDD4',
    text:         '#1C2212',
    textSecond:   '#97af3b',
    textMuted:    '#7A8B5E',
    border:       '#C8D4A0',
    borderFocus:  palette.olive,
    primary:      palette.olive,
    primaryDark:  palette.oliveDark,
    amber:        palette.amber,
    amberDark:    palette.amberDark,
    sage:         palette.sage,
  },
  dark: {
    background:   '#111A0C',
    card:         '#192110',
    input:        '#202C15',
    muted:        '#263318',
    text:         '#E8F0D4',
    textSecond:   '#AABF80',
    textMuted:    '#6A8040',
    border:       '#2E4018',
    borderFocus:  palette.olive,
    primary:      palette.olive,
    primaryDark:  palette.oliveDark,
    amber:        palette.amber,
    amberDark:    palette.amberDark,
    sage:         palette.sage,
  },
};